### PR TITLE
Update u_utils.pas

### PR DESCRIPTION
**Pull request by cedric-r**
Can't compile due to type error.

### CODE REVIEW

**Comment by pchev** [comment]
Hi Cedric,

Thank you to remind me about this issue, I have to fix that for FPC 3.2.0 in a hurry just before my holidays and have forgotten to make the fix compatible with previous FPC version.
With FPC 3.2.0 it compile with PULONG but crash at run time, so I change it to ULONG to work. It look like a overload problem for MkParseDisplayName in activex.pp.

I commit a fix with a conditional so it work with FPC 3.0.4 and 3.2.0. Tell me if this work for you.

For FPC 3.2.0 I also have to change the way the image is read from ASCOM because of SafeArray incompatibilities. This must work with FPC 3.0.4 but I am also interested by your confirmation.

**Comment by cedric-r** [comment]
Hi Patrick,

I've had the change for a while but always forgot to ask you about it.
Today I did some tidying up and found it again. I thought a pull request
was the best way to make sure I don't forget again.

I'll confirm your 2 questions tomorrow.

Should I upgrade to FPC 3.2.0 after that?

Thanks.

**Comment by pchev** [comment]
I upgrade to FPC 3.2.0 principally for arm64 support, I was using a beta version on arm64 before. 
If you upgrade you must also change to Lazarus 2.0.10

**Comment by cedric-r** [comment]
Hi Patrick,

It works fine with my older version of FPC. It didn't crash when reu either.

Thanks.

**Comment by pchev** [comment]
Thank you for testing!

**Pull request merged**
